# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - "2.7"

cache:
  directories:
    - "$HOME/.pip-cache/"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt  --download-cache $HOME/.pip-cache

# command to run tests, e.g. python setup.py test
script: nosetests


