# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
env:
    - ARCH=x86
language: python
sudo: false
python:
    - "2.7"

install: 
    - "pip install -r requirements.txt"


